allowBuilds:
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - '@payloadcms/db-postgres@3.90.0'
  - '@payloadcms/drizzle@3.90.0'
  - '@payloadcms/graphql@3.90.0'
  - '@payloadcms/live-preview-react@3.90.0'
  - '@payloadcms/live-preview@3.90.0'
  - '@payloadcms/next@3.90.0'
  - '@payloadcms/plugin-cloud-storage@3.90.0'
  - '@payloadcms/storage-vercel-blob@3.90.0'
  - '@payloadcms/translations@3.90.0'
  - '@payloadcms/ui@3.90.0'
  - payload@3.90.0
onlyBuiltDependencies:
  - esbuild
  - sharp
